"use client";

const sections = [
  {
    id: "healthcare",
    title: "Healthcare / Medical",
    intro:
      "Core skills for direct care, clinical support, documentation, safety, patient interaction, healthcare operations, medical software, and healthcare hard skills.",
    groups: [
      {
        role: "LPN / RN",
        skills: [
          "Patient care",
          "Medication administration",
          "Charting and documentation",
          "Care planning",
          "Wound care",
          "Vital signs",
          "Infection control",
          "Patient education",
          "IV therapy",
          "Teamwork with providers",
          "Patient assessment",
          "Catheter care",
          "Trach care",
          "Tube feeding support",
          "Blood glucose testing",
          "Medication reconciliation",
          "Discharge teaching",
          "Specimen collection",
          "Physician order follow-through",
          "EMR/EHR charting",
        ],
      },
      {
        role: "CNA / HHA",
        skills: [
          "Activities of daily living",
          "Bathing and grooming assistance",
          "Mobility and transfer support",
          "Feeding assistance",
          "Toileting support",
          "Vital signs",
          "Observation and reporting",
          "Companionship",
          "Infection prevention",
          "Resident dignity and safety",
          "Transfer and gait belt use",
          "Hoyer lift support",
          "Intake and output tracking",
          "Repositioning and pressure prevention",
          "Dementia care support",
          "Fall prevention",
          "Range of motion support",
          "Resident safety checks",
        ],
      },
      {
        role: "Medical Assistant",
        skills: [
          "Patient intake",
          "Scheduling",
          "Vital signs",
          "EMR/EHR documentation",
          "Specimen collection",
          "Injections",
          "Exam room prep",
          "Insurance verification",
          "Front desk support",
          "Provider assistance",
          "EKG",
          "Phlebotomy support",
          "Prior authorizations",
          "Sterilization",
          "Medication refill requests",
          "Referral coordination",
        ],
      },
      {
        role: "Medical Coding and Billing",
        skills: [
          "ICD-10",
          "CPT",
          "HCPCS",
          "Claims processing",
          "Insurance follow-up",
          "Denial resolution",
          "Billing accuracy",
          "EMR/EHR systems",
          "Payment posting",
          "Prior authorizations",
          "Medical terminology",
          "Coding audits",
          "Compliance",
          "HIPAA",
          "A/R follow-up",
          "Claim submission",
        ],
      },
      {
        role: "Phlebotomy",
        skills: [
          "Venipuncture",
          "Capillary sticks",
          "Specimen labeling",
          "Sample handling",
          "Patient identification",
          "Infection control",
          "Bedside manner",
          "Documentation",
          "Safety procedures",
          "Lab coordination",
          "Centrifuge use",
          "Chain of custody procedures",
          "Lab requisitions",
          "Specimen transport",
          "Attention to detail",
        ],
      },
      {
        role: "Pharmacy Tech",
        skills: [
          "Prescription processing",
          "Medication counting",
          "Medication prep",
          "Inventory control",
          "Insurance processing",
          "Customer service",
          "Data entry",
          "Dosage support",
          "Confidentiality",
          "Labeling accuracy",
          "Retail or hospital pharmacy workflow",
          "Prior authorization support",
          "Insurance adjudication",
          "Refill processing",
          "Controlled substance handling procedures",
        ],
      },
      {
        role: "Optometrist / Eye Care Support",
        skills: [
          "Patient exams",
          "Lens measurement",
          "Charting",
          "Diagnostic equipment use",
          "Patient education",
          "Scheduling",
          "Insurance verification",
          "Contact lens support",
          "Visual acuity testing",
          "Attention to detail",
        ],
      },
      {
        role: "Dental Hygienist / Dental Support",
        skills: [
          "Cleaning support",
          "Patient education",
          "Charting",
          "X-ray support",
          "Sterilization",
          "Periodontal assessment",
          "Infection control",
          "Instrument prep",
          "Scheduling support",
          "Bedside manner",
          "Dental software systems",
        ],
      },
      {
        role: "X-Ray Tech",
        skills: [
          "Imaging procedures",
          "Patient positioning",
          "Radiation safety",
          "Equipment operation",
          "Image documentation",
          "Provider collaboration",
          "Patient prep",
          "Anatomy knowledge",
          "Accuracy",
          "Compliance",
          "PACS",
          "Image processing",
        ],
      },
      {
        role: "EMS / Paramedic",
        skills: [
          "Emergency response",
          "Patient assessment",
          "CPR",
          "BLS",
          "ALS",
          "Trauma response",
          "Transport coordination",
          "Documentation",
          "Communication under pressure",
          "Emergency protocol knowledge",
          "Teamwork",
          "Scene safety",
          "Airway management",
          "ECG monitoring",
          "Triage",
          "Bleeding control",
        ],
      },
      {
        role: "Rehab Tech",
        skills: [
          "Patient mobility support",
          "Exercise assistance",
          "Therapy room setup",
          "Observation and reporting",
          "Scheduling support",
          "Sanitizing equipment",
          "Patient encouragement",
          "Teamwork",
          "Safety awareness",
          "Documentation support",
          "Transfer support",
          "Progress tracking",
        ],
      },
      {
        role: "Drug and Alcohol Counselor / Tech",
        skills: [
          "Client support",
          "Case notes",
          "Confidentiality",
          "Crisis support",
          "Treatment plan support",
          "Empathy",
          "Group facilitation",
          "Behavioral observation",
          "Community resources",
          "Documentation",
          "Intake documentation",
          "Progress notes",
          "Relapse prevention support",
        ],
      },
      {
        role: "Nursing Home Staff",
        skills: [
          "Long-term care support",
          "Resident safety",
          "ADL assistance",
          "Charting",
          "Dementia awareness",
          "Infection control",
          "Family communication",
          "Teamwork",
          "Patience",
          "Compliance",
        ],
      },
      {
        role: "Group Home / Disability Support Staff",
        skills: [
          "Daily living support",
          "Behavior support",
          "Medication reminders",
          "Transportation support",
          "Community integration",
          "Documentation",
          "Crisis de-escalation",
          "Resident dignity",
          "Safety monitoring",
          "Communication",
        ],
      },
      {
        role: "Occupational Therapist",
        skills: [
          "Patient assessment",
          "Treatment planning",
          "Rehabilitation support",
          "ADL training",
          "Documentation",
          "Patient education",
          "Mobility and function support",
          "Teamwork with providers",
          "Empathy",
          "Progress evaluation",
          "Adaptive equipment training",
          "Care coordination",
        ],
      },
      {
        role: "Dietitian",
        skills: [
          "Nutrition assessment",
          "Meal planning",
          "Patient education",
          "Documentation",
          "Health counseling",
          "Dietary compliance",
          "Communication",
          "Care coordination",
          "Wellness support",
          "Attention to detail",
        ],
      },
      {
        role: "Massage Therapist",
        skills: [
          "Body mechanics",
          "Client care",
          "Muscle tension relief",
          "Sanitation",
          "Scheduling",
          "Professionalism",
          "Client communication",
          "Anatomy knowledge",
          "Relaxation techniques",
          "Documentation",
        ],
      },
      {
        role: "Social Worker",
        skills: [
          "Case documentation",
          "Crisis support",
          "Advocacy",
          "Client assessment",
          "Community resources",
          "Care coordination",
          "Communication",
          "Empathy",
          "Confidentiality",
          "Problem solving",
          "Biopsychosocial assessment",
          "Discharge planning",
        ],
      },
      {
        role: "Case Manager",
        skills: [
          "Client follow-up",
          "Documentation",
          "Resource coordination",
          "Assessment",
          "Communication",
          "Scheduling",
          "Care planning support",
          "Advocacy",
          "Organization",
          "Confidentiality",
          "Referrals",
          "Utilization review support",
        ],
      },
      {
        role: "Healthcare Systems / Acronyms / Software",
        skills: [
          "EMR",
          "EHR",
          "MAR",
          "eMAR",
          "HIPAA",
          "ICD-10",
          "CPT",
          "HCPCS",
          "BLS",
          "CPR",
          "ALS",
          "EKG / ECG",
          "PACS",
          "EPIC",
          "Cerner",
          "Meditech",
          "eClinicalWorks",
          "Allscripts",
        ],
      },
    ],
  },
  {
    id: "customer-service",
    title: "Customer Service / Sales",
    intro:
      "Core skills for client-facing, support, outreach, and service-focused roles.",
    groups: [
      {
        role: "Customer Service",
        skills: [
          "Conflict resolution",
          "Active listening",
          "De-escalation",
          "CRM systems",
          "Complaint handling",
          "Multitasking",
          "Phone etiquette",
          "Problem solving",
          "Account support",
          "Professionalism",
        ],
      },
      {
        role: "Sales Representative / Canvasser",
        skills: [
          "Lead generation",
          "Relationship building",
          "Communication",
          "Persuasion",
          "Product knowledge",
          "Goal tracking",
          "Follow-up",
          "Territory outreach",
          "Customer service",
          "Professionalism",
        ],
      },
      {
        role: "Merchandiser",
        skills: [
          "Product placement",
          "Inventory checks",
          "Planogram setup",
          "Visual presentation",
          "Store support",
          "Attention to detail",
          "Organization",
          "Communication",
          "Stocking",
          "Time management",
        ],
      },
      {
        role: "Marketer",
        skills: [
          "Campaign support",
          "Communication",
          "Branding",
          "Content planning",
          "Audience awareness",
          "Organization",
          "Analytics awareness",
          "Creativity",
          "Project coordination",
          "Problem solving",
        ],
      },
      {
        role: "Designer",
        skills: [
          "Creativity",
          "Layout and composition",
          "Branding",
          "Visual communication",
          "Software proficiency",
          "Attention to detail",
          "Collaboration",
          "Revisions",
          "Presentation skills",
          "Project management",
        ],
      },
    ],
  },
  {
    id: "drivers",
    title: "Drivers",
    intro: "Core skills for commercial, passenger, and delivery driving roles.",
    groups: [
      {
        role: "CDL A / CDL B",
        skills: [
          "DOT compliance",
          "Route planning",
          "Safety inspections",
          "Logbooks and ELD",
          "Cargo securement",
          "Time management",
          "Defensive driving",
          "Customer delivery service",
          "Vehicle checks",
          "On-time delivery",
        ],
      },
      {
        role: "Non-CDL / Delivery",
        skills: [
          "Local routing",
          "Safe driving",
          "Loading and unloading",
          "Customer interaction",
          "Proof of delivery",
          "Schedule adherence",
          "Navigation tools",
          "Vehicle care",
          "Reliability",
          "Time management",
        ],
      },
      {
        role: "Passenger / Limo / Livery / Taxi",
        skills: [
          "Passenger safety",
          "Customer service",
          "Punctuality",
          "Route knowledge",
          "Clean vehicle upkeep",
          "Professional appearance",
          "Defensive driving",
          "Cash and payment handling",
          "Trip documentation",
          "Communication",
        ],
      },
    ],
  },
  {
    id: "warehouse",
    title: "Warehouse / Forklift / Logistics",
    intro:
      "Core skills for shipping, receiving, inventory, powered equipment, dispatch, and fulfillment roles.",
    groups: [
      {
        role: "Warehouse",
        skills: [
          "Picking and packing",
          "Shipping and receiving",
          "Inventory control",
          "RF scanner use",
          "Palletizing",
          "Loading and unloading",
          "Order accuracy",
          "Safety compliance",
          "Labeling",
          "Teamwork",
        ],
      },
      {
        role: "Forklift",
        skills: [
          "Forklift operation",
          "Pallet movement",
          "Loading and unloading",
          "Warehouse safety",
          "Inventory movement",
          "Equipment checks",
          "Order staging",
          "Shipping support",
          "Accuracy",
          "Productivity",
        ],
      },
      {
        role: "Logistics",
        skills: [
          "Dispatching",
          "Shipment tracking",
          "Route coordination",
          "Inventory movement",
          "Documentation",
          "Vendor communication",
          "Scheduling",
          "Compliance",
          "Problem solving",
          "Data entry",
        ],
      },
    ],
  },
  {
    id: "manufacturing",
    title: "Manufacturing / Aerospace / Oil Tech",
    intro:
      "Core skills for production, assembly, regulated work, inspection, and industrial operations.",
    groups: [
      {
        role: "Manufacturing",
        skills: [
          "Machine operation",
          "Assembly",
          "Quality inspection",
          "Production line work",
          "Safety procedures",
          "Measuring tools",
          "Troubleshooting",
          "Packaging",
          "Documentation",
          "Efficiency",
        ],
      },
      {
        role: "Aerospace",
        skills: [
          "Precision assembly",
          "Blueprint reading",
          "Quality standards",
          "Safety compliance",
          "Documentation",
          "Mechanical aptitude",
          "Inspection",
          "Tool usage",
          "Production support",
          "Attention to detail",
        ],
      },
      {
        role: "Oil Tech",
        skills: [
          "Equipment monitoring",
          "Preventive maintenance",
          "Troubleshooting",
          "Safety compliance",
          "Pressure checks",
          "Fluid handling",
          "Mechanical aptitude",
          "Inspection",
          "Documentation",
          "Problem solving",
          "Field support",
          "Tool usage",
          "Environmental awareness",
          "Site safety",
          "Operational checks",
        ],
      },
    ],
  },
  {
    id: "hospitality-cleaning",
    title: "Hospitality / Cleaning / Food Service",
    intro:
      "Core skills for guest service, housekeeping, kitchen support, and food operations.",
    groups: [
      {
        role: "Hospitality",
        skills: [
          "Guest service",
          "Reservations",
          "Front desk support",
          "Housekeeping standards",
          "Event support",
          "Multitasking",
          "Communication",
          "Problem resolution",
          "Professionalism",
          "Teamwork",
        ],
      },
      {
        role: "Housekeeping",
        skills: [
          "Room cleaning",
          "Sanitation",
          "Linen changes",
          "Supply restocking",
          "Attention to detail",
          "Guest readiness",
          "Time management",
          "Safety procedures",
          "Organization",
          "Reliability",
        ],
      },
      {
        role: "Housewife / Household Manager",
        skills: [
          "Household organization",
          "Scheduling",
          "Budgeting",
          "Meal planning",
          "Multitasking",
          "Caregiving support",
          "Cleaning coordination",
          "Time management",
          "Problem solving",
          "Adaptability",
        ],
      },
      {
        role: "Chef / Cook",
        skills: [
          "Menu prep",
          "Food safety",
          "Knife skills",
          "Cooking techniques",
          "Plating and presentation",
          "Kitchen organization",
          "Time management",
          "Inventory awareness",
          "Sanitation",
          "Teamwork",
        ],
      },
      {
        role: "Dishwasher",
        skills: [
          "Dishwashing",
          "Sanitation",
          "Kitchen cleanliness",
          "Time management",
          "Organization",
          "Safety procedures",
          "Support to kitchen staff",
          "Reliability",
          "Attention to detail",
          "Fast-paced work",
        ],
      },
      {
        role: "Prep Cook / Kitchen Prep",
        skills: [
          "Ingredient prep",
          "Portioning",
          "Food safety",
          "Knife skills",
          "Station setup",
          "Labeling and storage",
          "Sanitation",
          "Teamwork",
          "Speed and efficiency",
          "Recipe support",
        ],
      },
      {
        role: "Food Service",
        skills: [
          "Food prep",
          "Sanitation",
          "Food safety",
          "Cashiering",
          "Order accuracy",
          "Customer service",
          "Kitchen support",
          "Stocking",
          "Teamwork",
          "Speed and efficiency",
        ],
      },
    ],
  },
  {
    id: "education-support",
    title: "Education / Support / Human Services",
    intro:
      "Core skills for classrooms, tutoring, coaching, training, and support-based roles.",
    groups: [
      {
        role: "Paraprofessional",
        skills: [
          "Classroom support",
          "Student assistance",
          "Behavior support",
          "Communication",
          "Documentation",
          "Teamwork with teachers",
          "Patience",
          "Adaptability",
          "Instructional support",
          "Supervision",
        ],
      },
      {
        role: "Trainer",
        skills: [
          "Onboarding",
          "Coaching",
          "Presentation skills",
          "Communication",
          "Curriculum support",
          "Knowledge transfer",
          "Feedback delivery",
          "Engagement",
          "Organization",
          "Leadership",
        ],
      },
      {
        role: "Coach",
        skills: [
          "Motivation",
          "Leadership",
          "Instruction",
          "Communication",
          "Teamwork",
          "Planning",
          "Performance feedback",
          "Mentoring",
          "Adaptability",
          "Problem solving",
        ],
      },
      {
        role: "Tutor",
        skills: [
          "Subject support",
          "Lesson planning",
          "Communication",
          "Patience",
          "Active listening",
          "Adaptability",
          "Encouragement",
          "Progress tracking",
          "Organization",
          "Student engagement",
        ],
      },
    ],
  },
  {
    id: "admin-clerical-legal",
    title: "Admin / Clerical / Legal / Business",
    intro:
      "Core skills for office support, legal support, organization, communication, and business operations.",
    groups: [
      {
        role: "Admin / Clerical",
        skills: [
          "Scheduling",
          "Data entry",
          "Document preparation",
          "Calendar management",
          "Filing",
          "Phone support",
          "Email communication",
          "Microsoft Office",
          "Records management",
          "Organization",
        ],
      },
      {
        role: "Paralegal",
        skills: [
          "Legal research",
          "Document preparation",
          "Case file organization",
          "Scheduling",
          "Client communication",
          "Attention to detail",
          "Confidentiality",
          "Drafting support",
          "Records management",
          "Time management",
        ],
      },
      {
        role: "Financial Advisor",
        skills: [
          "Client relationship management",
          "Financial planning",
          "Budgeting",
          "Investment guidance",
          "Communication",
          "Compliance awareness",
          "Documentation",
          "Presentation skills",
          "Confidentiality",
          "Problem solving",
        ],
      },
      {
        role: "Entrepreneur",
        skills: [
          "Business planning",
          "Customer service",
          "Communication",
          "Sales",
          "Budgeting",
          "Problem solving",
          "Adaptability",
          "Marketing",
          "Leadership",
          "Time management",
        ],
      },
    ],
  },
  {
    id: "it-helpdesk",
    title: "IT / Help Desk / Coding",
    intro:
      "Core skills for troubleshooting, user support, networking basics, coding tools, systems, software, and technical service roles.",
    groups: [
      {
        role: "IT / Help Desk",
        skills: [
          "Troubleshooting",
          "Hardware setup",
          "Software installation",
          "Printer support",
          "Device imaging",
          "Password resets",
          "User account management",
          "Ticketing systems",
          "Remote desktop support",
          "Network basics",
          "VPN support",
          "Wi-Fi troubleshooting",
          "Operating system support",
          "Microsoft 365 support",
          "Google Workspace support",
          "MFA setup",
          "Access provisioning",
          "System updates",
          "Documentation",
        ],
      },
      {
        role: "Help Desk / Desktop Support",
        skills: [
          "Active Directory",
          "Azure AD / Entra ID",
          "Office 365",
          "Outlook troubleshooting",
          "Teams support",
          "Windows support",
          "macOS support",
          "Mobile device support",
          "Printer and scanner setup",
          "Software deployment",
          "File permissions",
          "Shared drives",
          "Basic networking",
          "Ticket escalation",
          "SLA awareness",
        ],
      },
      {
        role: "Networking Basics",
        skills: [
          "TCP/IP",
          "DNS",
          "DHCP",
          "VPN",
          "LAN/WAN",
          "Routers and switches",
          "IP configuration",
          "Ping / traceroute",
          "Firewall basics",
          "Network connectivity checks",
        ],
      },
      {
        role: "Coding / Technical Tools",
        skills: [
          "HTML",
          "CSS",
          "JavaScript",
          "Python",
          "SQL",
          "JSON",
          "API basics",
          "Git",
          "GitHub",
          "VS Code",
          "Command line basics",
          "PowerShell basics",
          "Scripting basics",
          "Debugging basics",
          "Data validation",
          "Automation basics",
        ],
      },
      {
        role: "IT Systems / Software / Acronyms",
        skills: [
          "ITSM",
          "SLA",
          "KPI",
          "VPN",
          "DNS",
          "DHCP",
          "TCP/IP",
          "MFA",
          "SSO",
          "AD",
          "Azure AD / Entra",
          "OS",
          "API",
          "SQL",
          "HTML",
          "CSS",
          "JS",
          "QA",
          "UI",
          "UX",
          "CRM",
          "ERP",
          "VoIP",
          "Microsoft 365",
          "Outlook",
          "Teams",
          "SharePoint",
          "OneDrive",
          "Google Workspace",
          "Jira",
          "ServiceNow",
          "Zendesk",
          "Freshdesk",
          "Salesforce",
          "HubSpot",
          "Slack",
          "Zoom",
          "Visual Studio Code",
        ],
      },
    ],
  },
  {
    id: "trades-construction",
    title: "Trades / Construction / Field Work",
    intro:
      "Core skills for skilled trades, site work, repair, installation, maintenance, and physical labor roles.",
    groups: [
      {
        role: "HVAC",
        skills: [
          "System installation",
          "Troubleshooting",
          "Repairs",
          "Preventive maintenance",
          "Safety compliance",
          "Equipment diagnostics",
          "Blueprint reading",
          "Customer communication",
          "Tool usage",
          "Time management",
        ],
      },
      {
        role: "Plumber",
        skills: [
          "Pipe installation",
          "Repairs",
          "Troubleshooting",
          "Blueprint reading",
          "Safety compliance",
          "Preventive maintenance",
          "Tool usage",
          "Inspections",
          "Customer communication",
          "Problem solving",
        ],
      },
      {
        role: "Welding",
        skills: [
          "Blueprint reading",
          "Metal fabrication",
          "Welding techniques",
          "Equipment safety",
          "Measuring",
          "Quality inspection",
          "Precision",
          "Tool usage",
          "Production support",
          "Attention to detail",
        ],
      },
      {
        role: "Electrician",
        skills: [
          "Wiring",
          "Electrical troubleshooting",
          "Blueprint reading",
          "Safety compliance",
          "Code awareness",
          "Installations",
          "Inspections",
          "Tool usage",
          "Problem solving",
          "Maintenance",
        ],
      },
      {
        role: "Journeyman",
        skills: [
          "Trade expertise",
          "Blueprint reading",
          "Job site safety",
          "Troubleshooting",
          "Installation",
          "Repairs",
          "Leadership",
          "Mentoring helpers",
          "Tool usage",
          "Compliance",
        ],
      },
      {
        role: "Steel Work",
        skills: [
          "Structural assembly",
          "Measuring",
          "Blueprint reading",
          "Fabrication",
          "Rigging awareness",
          "Safety procedures",
          "Heavy equipment coordination",
          "Welding support",
          "Teamwork",
          "Precision",
        ],
      },
      {
        role: "Construction",
        skills: [
          "Site prep",
          "Material handling",
          "Tool usage",
          "Measurements",
          "Blueprint awareness",
          "Safety compliance",
          "Teamwork",
          "Physical stamina",
          "Problem solving",
          "Reliability",
        ],
      },
      {
        role: "Roofing",
        skills: [
          "Roof installation",
          "Repairs",
          "Ladder safety",
          "Measuring",
          "Material handling",
          "Weather awareness",
          "Safety compliance",
          "Attention to detail",
          "Teamwork",
          "Physical stamina",
        ],
      },
      {
        role: "Trade",
        skills: [
          "Hand and power tools",
          "Safety compliance",
          "Blueprint reading",
          "Repairs",
          "Installation",
          "Troubleshooting",
          "Measurements",
          "Teamwork",
          "Reliability",
          "Problem solving",
        ],
      },
      {
        role: "Landscape",
        skills: [
          "Lawn care",
          "Planting",
          "Trimming",
          "Outdoor maintenance",
          "Tool usage",
          "Irrigation awareness",
          "Time management",
          "Physical stamina",
          "Safety procedures",
          "Teamwork",
        ],
      },
      {
        role: "Farmer",
        skills: [
          "Crop care",
          "Equipment use",
          "Livestock support",
          "Irrigation",
          "Harvesting",
          "Safety procedures",
          "Physical stamina",
          "Time management",
          "Maintenance support",
          "Problem solving",
        ],
      },
    ],
  },
  {
    id: "retail",
    title: "Retail",
    intro: "Core skills for store, sales floor, and customer-facing retail roles.",
    groups: [
      {
        role: "Retail",
        skills: [
          "POS systems",
          "Cash handling",
          "Customer service",
          "Merchandising",
          "Stocking",
          "Upselling",
          "Returns and exchanges",
          "Store presentation",
          "Teamwork",
          "Inventory support",
        ],
      },
    ],
  },
  {
    id: "maintenance-security-auto",
    title: "Maintenance / Security / Auto",
    intro:
      "Core skills for building upkeep, security, automotive work, and detail-oriented facility roles.",
    groups: [
      {
        role: "Maintenance",
        skills: [
          "Preventive maintenance",
          "Repairs",
          "Troubleshooting",
          "Work orders",
          "Hand and power tools",
          "Safety compliance",
          "Inspections",
          "Building upkeep",
          "Time management",
          "Problem solving",
        ],
      },
      {
        role: "Janitorial",
        skills: [
          "Floor care",
          "Sanitation",
          "Trash removal",
          "Restroom cleaning",
          "Supply restocking",
          "Safety procedures",
          "Attention to detail",
          "Time management",
          "Reliability",
          "Building cleanliness",
        ],
      },
      {
        role: "Security",
        skills: [
          "Surveillance",
          "Incident reporting",
          "Access control",
          "Patrols",
          "De-escalation",
          "Emergency response",
          "Communication",
          "Observation",
          "Professionalism",
          "Policy enforcement",
        ],
      },
      {
        role: "Mechanic",
        skills: [
          "Diagnostics",
          "Preventive maintenance",
          "Brake and suspension repair",
          "Engine repair",
          "Tool usage",
          "Safety compliance",
          "Inspections",
          "Problem solving",
          "Documentation",
          "Customer communication",
        ],
      },
      {
        role: "Car Shop Detailer",
        skills: [
          "Interior detailing",
          "Exterior washing",
          "Buffing and polishing",
          "Vacuuming",
          "Stain removal",
          "Vehicle presentation",
          "Chemical safety",
          "Time management",
          "Attention to detail",
          "Teamwork",
        ],
      },
      {
        role: "Lifeguard",
        skills: [
          "Water safety",
          "Surveillance",
          "CPR and first aid",
          "Emergency response",
          "Communication",
          "Rule enforcement",
          "Rescue readiness",
          "Attention to detail",
          "Professionalism",
          "Teamwork",
        ],
      },
    ],
  },
  {
    id: "creative-specialty",
    title: "Creative / Specialty Roles",
    intro:
      "Core skills for specialty, apparel, presentation, and independent service roles.",
    groups: [
      {
        role: "Seamstress",
        skills: [
          "Sewing",
          "Alterations",
          "Measuring",
          "Fabric handling",
          "Pattern reading",
          "Attention to detail",
          "Time management",
          "Quality control",
          "Repairs",
          "Customer requests",
        ],
      },
    ],
  },
];

export default function IndustryCoreSkillsPage() {
  return (
    <main style={styles.page}>
      <div style={styles.shell}>
        <section style={styles.heroCard}>
          <p style={styles.kicker}>Career ToolKit</p>
          <h1 style={styles.title}>Industry Core Skills</h1>
          <p style={styles.subtitle}>
            Browse common core skills by industry and role. Use these lists to
            help build your resume, cover letter, interview talking points, and
            job application language.
          </p>

          <div style={styles.heroButtons}>
            <a href="/career-toolkit" style={styles.linkButton}>
              Back to Career ToolKit
            </a>
          </div>
        </section>

        <section style={styles.jumpCard}>
          <p style={styles.sectionKicker}>Jump To</p>
          <div style={styles.jumpGrid}>
            {sections.map((section) => (
              <a key={section.id} href={`#${section.id}`} style={styles.jumpLink}>
                {section.title}
              </a>
            ))}
          </div>
        </section>

        <section style={styles.sectionsWrap}>
          {sections.map((section) => (
            <article key={section.id} id={section.id} style={styles.sectionCard}>
              <p style={styles.sectionKicker}>Industry</p>
              <h2 style={styles.sectionTitle}>{section.title}</h2>
              <p style={styles.sectionIntro}>{section.intro}</p>

              <div style={styles.groupWrap}>
                {section.groups.map((group) => (
                  <div key={group.role} style={styles.groupCard}>
                    <h3 style={styles.groupTitle}>{group.role}</h3>
                    <div style={styles.skillGrid}>
                      {group.skills.map((skill) => (
                        <div key={skill} style={styles.skillPill}>
                          {skill}
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </article>
          ))}
        </section>
      </div>
    </main>
  );
}

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "linear-gradient(180deg, #050505 0%, #0d0d0f 100%)",
    color: "#e7e7e7",
    padding: "32px 24px",
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  shell: {
    maxWidth: "1380px",
    margin: "0 auto",
    display: "grid",
    gap: "24px",
  },
  heroCard: {
    background: "linear-gradient(180deg, #141414 0%, #181818 100%)",
    border: "1px solid #262626",
    borderRadius: "24px",
    padding: "24px",
  },
  jumpCard: {
    background: "linear-gradient(180deg, #141414 0%, #181818 100%)",
    border: "1px solid #262626",
    borderRadius: "24px",
    padding: "24px",
  },
  sectionsWrap: {
    display: "grid",
    gap: "20px",
  },
  sectionCard: {
    background: "linear-gradient(180deg, #141414 0%, #181818 100%)",
    border: "1px solid #262626",
    borderRadius: "24px",
    padding: "24px",
    scrollMarginTop: "100px",
  },
  kicker: {
    margin: "0 0 8px",
    color: "#9a9a9a",
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
  },
  title: {
    margin: "0 0 10px",
    fontSize: "40px",
    fontWeight: 600,
    color: "#f5f5f5",
  },
  subtitle: {
    margin: 0,
    color: "#c8c8c8",
    fontSize: "16px",
    lineHeight: 1.7,
    maxWidth: "900px",
  },
  heroButtons: {
    display: "flex",
    gap: "12px",
    marginTop: "18px",
    flexWrap: "wrap",
  },
  linkButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    textDecoration: "none",
    padding: "12px 16px",
    borderRadius: "16px",
    border: "1px solid #3a3a3a",
    background: "#111111",
    color: "#f5f5f5",
    fontWeight: 700,
  },
  sectionKicker: {
    margin: "0 0 8px",
    color: "#9a9a9a",
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
  },
  jumpGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "10px",
  },
  jumpLink: {
    textDecoration: "none",
    color: "#f5f5f5",
    background: "#101010",
    border: "1px solid #2f2f2f",
    borderRadius: "14px",
    padding: "12px 14px",
    fontSize: "14px",
    fontWeight: 600,
  },
  sectionTitle: {
    margin: "0 0 10px",
    fontSize: "30px",
    fontWeight: 600,
    color: "#f5f5f5",
  },
  sectionIntro: {
    margin: "0 0 18px",
    color: "#c8c8c8",
    fontSize: "15px",
    lineHeight: 1.7,
  },
  groupWrap: {
    display: "grid",
    gap: "14px",
  },
  groupCard: {
    background: "#101010",
    border: "1px solid #2d2d2d",
    borderRadius: "18px",
    padding: "18px",
  },
  groupTitle: {
    margin: "0 0 14px",
    fontSize: "22px",
    fontWeight: 600,
    color: "#f5f5f5",
  },
  skillGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
  },
  skillPill: {
    padding: "10px 12px",
    borderRadius: "999px",
    background: "#111827",
    border: "1px solid #374151",
    color: "#f3f4f6",
    fontSize: "14px",
    lineHeight: 1.4,
  },
};
